# Path to FAI-index of reference used
#     Example -  reference_fai: /path/to/your/reference/hg19/hg19.fa.fai
reference_fai: "null"

# Samplesheet for specifying sample names
samples: config/samples.tsv

# Location of input data
input_location: raw_data

# Directory for writing output directories and files to (if '', write to same directory as pipeline)
output_directory: ''

# Path to targets BED file (can be gzipped)
#     Example - targets: example/targets.bed.gz
targets: "null"

# Step size of values along x-axis of multiscale plot
# The multiscale plot will find the average methylation value in a bin size of 10^X (X defined by bounds below) centered
#     on each x value as determined by x_step
x_step: 10000

# Bounds of the exponents used when generating the multiscale plot
# Exponents will run from bounds['min'] to bounds['max'], inclusive, with step size of bounds['step']
bounds:
    min: 4
    max: 7
    step: 0.1

# Environment module paths used in "module load <string>" (pending you have a module system available)
# By default, Snakemake will attempt to use conda to install the necessary tools. If you don't want to use conda and
#     system does not have environment modules, then executables for all required tools much be in your PATH
# Required tools: bedtools
envmodules:
    bedtools: "null"

# Parameters to use when running pipeline in a cluster environment
hpc_parameters:
    low_walltime: 1:00:00
    mid_walltime: 12:00:00
    max_walltime: 24:00:00
    low_memory_gb: 10
    mid_memory_gb: 100
    max_memory_gb: 250
